spring.application.name=appointmentBooking
spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.zxlxwhrodxxfopqijutm
spring.datasource.password=apptbooking440
spring.jpa.hibernate.ddl-auto=update
server.port=8081
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1