spring.application.name=appointmentBooking
spring.datasource.url=jdbc:postgresql://db.zxlxwhrodxxfopqijutm.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=apptbooking440
spring.jpa.hibernate.ddl-auto=update